from fastapi import APIRouter, Depends, Query, Path, Response
from app.utils.app_states import get_async_supabase_client, get_async_httpx_client
from app.utils.user_auth import verify_jwt_and_get_user_id
from app.services.gmail.gmail_channel_oauth_services import (
    initialize_gmail_channel_create_and_oauth,
    gmail_channel_oauth_complete_callback,
    gmail_channel_reoauth_process,
)
from uuid import UUID
from supabase._async.client import AsyncClient
from httpx import AsyncClient
from app.models.oauth_process_models import GmailOAuthFlowResponse, GmailOAuthCallbackCompletionResponse


gmail_channel_oauth_router = APIRouter(prefix="/gmail/channel", tags=["oauth"])


# this is to essentially create a new gmail channel and see if we need a whole gmail oauth flow for this user or not
@gmail_channel_oauth_router.post("/initialize/{project_id}", response_model=GmailOAuthFlowResponse)
async def initialize_gmail_channel_create_and_oauth_handler(
    project_id: str = Path(...),  # "..." means this is a required path parameter
    supabase: AsyncClient = Depends(get_async_supabase_client),
    user_id: UUID = Depends(verify_jwt_and_get_user_id),
):
    print("/gmail/oauth/initialize POST route reached")
    return await initialize_gmail_channel_create_and_oauth(supabase, project_id, user_id)


@gmail_channel_oauth_router.post("/refresh", response_model=GmailOAuthFlowResponse)
async def refresh_gmail_oauth_handler(
    supabase: AsyncClient = Depends(get_async_supabase_client),
    user_id: UUID = Depends(verify_jwt_and_get_user_id),
):
    """
    Generate a new OAuth URL when any credentials and refresh token are invalidated.
    Clears existing invalid credentials.
    """
    print("/gmail/oauth/refresh POST route reached")
    return await gmail_channel_reoauth_process(supabase, user_id)


# from above request, user should get a google gmail oauth url that nav to Google's OAuth URL (generated by our fastapi side only without connecting to GCP yet) page
# once user log in and finish the consent, it will connect back to Google's Authorization Server to processes the Consent and return the "authorization code"
# Google then sends an HTTP redirect (302) back to the user’s browser same page -> it is the user’s browser that follows redirect and then sends redirect GET request.
# This has to be GET request as this is browser request
# this whole flow here is fully automatic.
@gmail_channel_oauth_router.get("/callback", response_model=GmailOAuthCallbackCompletionResponse)
async def gmail_channel_oauth_complete_callback_handler(
    code: str = Query(...),
    state: str = Query(...),  # state parameter
    supabase: AsyncClient = Depends(get_async_supabase_client),
    httpx_client: AsyncClient = Depends(get_async_httpx_client),
):
    print("/gmail/oauth/callback GET route reached")
    return await gmail_channel_oauth_complete_callback(supabase, httpx_client, code, state)
